
package GUI;

import bd_conexion.Conexion1;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class Informe extends javax.swing.JFrame {

    int xMouse, yMouse;
    Conexion1 conectar = Conexion1.getInstancia();

    public Informe() {
        initComponents();
        txtInfREnd.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfREnd = new javax.swing.JTextArea();
        txtFechaRegistro = new javax.swing.JTextField();
        labelMostrarInforemeRendimiento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        panelBotonCerrar = new javax.swing.JPanel();
        labelX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(56, 60, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInfREnd.setColumns(20);
        txtInfREnd.setRows(5);
        jScrollPane1.setViewportView(txtInfREnd);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 681, 190));

        txtFechaRegistro.setBackground(new java.awt.Color(56, 60, 74));
        txtFechaRegistro.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaRegistro.setText("Ingrese la fecha de registro");
        txtFechaRegistro.setBorder(null);
        txtFechaRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaRegistroMousePressed(evt);
            }
        });
        txtFechaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        labelMostrarInforemeRendimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24.png"))); // NOI18N
        labelMostrarInforemeRendimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMostrarInforemeRendimientoMouseClicked(evt);
            }
        });
        jPanel1.add(labelMostrarInforemeRendimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 10));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-health-graph-50.png"))); // NOI18N
        jLabel2.setText("Ver Informe de Rendimiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 50));

        panelBarra.setBackground(new java.awt.Color(34, 36, 45));
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });

        panelBotonCerrar.setBackground(new java.awt.Color(34, 36, 45));

        labelX.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        labelX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelX.setText("X");
        labelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBotonCerrarLayout = new javax.swing.GroupLayout(panelBotonCerrar);
        panelBotonCerrar.setLayout(panelBotonCerrarLayout);
        panelBotonCerrarLayout.setHorizontalGroup(
            panelBotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonCerrarLayout.setVerticalGroup(
            panelBotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addGap(0, 680, Short.MAX_VALUE)
                .addComponent(panelBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRegistroActionPerformed

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraMouseDragged

    private void labelXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXMouseClicked

        this.setVisible(false);
    }//GEN-LAST:event_labelXMouseClicked

    private void labelXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXMouseEntered
        panelBotonCerrar.setBackground(Color.red);
        labelX.setForeground(Color.decode("#22242D"));
    }//GEN-LAST:event_labelXMouseEntered

    private void labelXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXMouseExited
        panelBotonCerrar.setBackground(Color.decode("#22242D"));
        labelX.setForeground(Color.black);
    }//GEN-LAST:event_labelXMouseExited

    private void labelMostrarInforemeRendimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarInforemeRendimientoMouseClicked
        txtInfREnd.setText(mostrarInformeRendimiento());
    }//GEN-LAST:event_labelMostrarInforemeRendimientoMouseClicked

    private void txtFechaRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaRegistroMousePressed
        if (txtFechaRegistro.getText().equals("Ingrese la fecha de registro")) {
            txtFechaRegistro.setText("");
            txtFechaRegistro.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaRegistroMousePressed

    public String mostrarInformeRendimiento() {
        StringBuilder contenido = new StringBuilder();
        contenido.append("ID del Equipo                  Fech.Registro de Rendimiento                  Tiempo de Actividad                  Tiempo de Inactividad               Latencia                  Ancho de Banda                  Uso de Recurso\n\n");
        txtInfREnd.setText(" ");
        try {
            boolean existe = false;
            Connection conexion = conectar.conectar();
            String fechaRegistro = txtFechaRegistro.getText().trim();
            PreparedStatement buscarRendimiento = conexion.prepareStatement("SELECT * FROM informe_rendimiento ");
            ResultSet consultaInformeRendimiento = buscarRendimiento.executeQuery();
            while (consultaInformeRendimiento.next()) {
                PreparedStatement buscarEquipo = conexion.prepareStatement("SELECT * FROM rendimiento WHERE fecha_registro='" + fechaRegistro + "' ORDER BY fecha_registro DESC LIMIT 1");
                ResultSet consultaRendimiento = buscarEquipo.executeQuery();
                if (consultaRendimiento.next()) {
                    existe = true;
                    if (existe == true) {
                        if (consultaRendimiento.getString(3).equals(fechaRegistro)) {
                            contenido.append(String.format("%-60s%-50s%-50s%-40s%-40s%-40s%-40s%n", consultaRendimiento.getString(2), consultaRendimiento.getString(3), consultaInformeRendimiento.getString(3), consultaInformeRendimiento.getString(4), consultaRendimiento.getString(4), consultaRendimiento.getString(5), consultaRendimiento.getString(6)));
                        }
                    }
                }
            }

            conectar.cerrarConexion();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
        return contenido.toString();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            FlatArcDarkOrangeIJTheme.setup();
            UIManager.put("Button.arc", 999);
            UIManager.put("TextComponent.arc", 999);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMostrarInforemeRendimiento;
    private javax.swing.JLabel labelX;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelBotonCerrar;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextArea txtInfREnd;
    // End of variables declaration//GEN-END:variables
}
